(ns vijion.util)

(def ^:const block-unit 10000)

     
                                                                                
      
(def ^:const num-processors 1)

(defn pop-queue!
  [queue]
       
         
                          
                       
        
        
  nil)

(defn pick-fn
  [data len width]
  (fn [idx ox oy]
    (let [i (+ idx ox (* width oy))]
      (cond
       (< i 0) nil
       (< i len) (nth data i)
       :else nil))))

(defn pick
  [data len width idx ox oy]
  (let [i (+ idx ox (* width oy))]
    (cond
     (< i 0) nil
     (< i len) (nth data i)
     :else nil)))

(def abs
                     
         #(.abs js/Math %))

(def sqrt
                      
         #(.sqrt js/Math %))

;;;;;;;;;;;; This file autogenerated from src/cljx/vijion/util.cljx
